; queries/highlights.scm

(keyword_select) @keyword
(keyword_from) @keyword
(keyword_where) @keyword
(keyword_group) @keyword
(keyword_by) @keyword
(keyword_order) @keyword
(keyword_extend) @keyword
(keyword_set) @keyword
(keyword_drop) @keyword
(keyword_rename) @keyword
(keyword_aggregate) @keyword
(keyword_join) @keyword
(keyword_inner) @keyword
(keyword_outer) @keyword
(keyword_left) @keyword
(keyword_right) @keyword
(keyword_full) @keyword
(keyword_cross) @keyword
(keyword_on) @keyword
(keyword_using) @keyword
(keyword_limit) @keyword
(keyword_offset) @keyword
(keyword_call) @keyword
(keyword_window) @keyword
(keyword_as) @keyword
(keyword_distinct) @keyword
(keyword_over) @keyword
(keyword_partition) @keyword
(keyword_and) @keyword
(keyword_or) @keyword
(keyword_asc) @keyword
(keyword_desc) @keyword
(keyword_with) @keyword
(keyword_recursive) @keyword
(keyword_is) @keyword
(keyword_not) @keyword
(keyword_null) @constant.builtin  ; NULL is often highlighted as a constant
(keyword_true) @boolean
(keyword_false) @boolean
(keyword_between) @keyword
(keyword_in) @keyword
(keyword_like) @keyword
(keyword_case) @keyword
(keyword_when) @keyword
(keyword_then) @keyword
(keyword_else) @keyword
(keyword_end) @keyword
(keyword_having) @keyword

"|>" @operator
"=" @operator
"<" @operator
">" @operator
"+" @operator
"-" @operator
"*" @operator
"/" @operator

(string) @string
(number) @number
(comment) @comment
(function_name) @function
(identifier) @variable
